- title: Getting started
  link: /
  items:
    - title: Welcome
      link: /
    - title: Themes and styling
      link: /behaviours/ThemeProvider/
    - title: Using Resouces
      link: /using-static-resources.html

- title: Forms
  link: /
  items:
    - title: Forms
      link: /forms.html
    - title: TextInput
      link: /molecules/TextInput/
    - title: Checkbox
      link: /molecules/Checkbox/
